#!/bin/bash

./configure target="RLLibTestDebug" \
               cflags="-I. -I./src -I./test -I./simulation -ggdb -Wno-deprecated -fPIC -fno-rtti" \
               lflags="-lpthread" \
               ignore="'visualization/*'" \
               bin="RLLibTest"
