#!/bin/bash

./configure target="RLLibTestDebug" \
               cflags="-I. -I./src -I./test -I./simulation -ggdb -Wno-deprecated -fPIC" \
               lflags="" \
               ignore="'visualization/*'" \
               bin="RLLibTest"
